// @flow

export const ADD_WORKED_COMPANY_NAME = 'ADD_WORKED_COMPANY_NAME';
export const ADD_HEADING = 'ADD_HEADING';
export const ADD_DESCRIPTION = 'ADD_DESCRIPTION';
export const ADD_PRICE_LIST = 'ADD_PRICE_LIST';
export const ADD_COMPANY_LOGO = 'ADD_COMPANY_LOGO';
export const EDIT_PRICE_LIST = 'EDIT_PRICE_LIST';
export const DELETE_PRICE_LIST = 'DELETE_PRICE_LIST';
export const SET_EDIT_PRICELIST = 'SET_EDIT_PRICE_LIST';