// @flow

export const ADD_COMPANY_NAME = ADD_COMOANU_NAME;
export const ADD_WORKED_COMPANY_NAME = ADD_WORKED_COMOANY_NAME;
export const ADD_HEADING = ADD_HEADING;
export const ADD_PRICE_LIST = ADD_PRICE_LIST;
export const ADD_LOGO = ADD_LOGO;